name: IT-Room CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: itroom-runner-set

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: Just a test
